### ISSUE TITLE
OpenSAML 3?

### ISSUE THREAD

**Issue by martin-lindstrom** [Governikus/eIDAS-Node-SDK#20]
You may want to consider using OpenSAML 3 since OpenSAML 2 has reached end-of-life.

**Comment by sijpma** [comment]
You can find the OpenSAML 3 version over here: https://github.com/Dictu/eIDAS-Node-SDK-3

**Comment by bennypi** [comment]
In addition to the dutch version, we included the SDK into the German eIDAS Middleware and updated to OpenSAML 3, see here: https://github.com/Governikus/eidas-middleware/tree/master/eidas-starterkit

This repository is no longer actively maintained and may be deleted in the future.
