### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by lekarlr** [Governikus/eIDAS-Node-SDK#8]
Hello, can you provide full example?

**Comment by AndreasHohnholt** [comment]
Hello lekarlr,

can you describe what the example should include?
On the Startpage you find an example to create a request and to parse a response.

**Comment by lekarlr** [comment]
do you have a validation example?

**Comment by AndreasHohnholt** [comment]
EidasSaml.ValidateXMLRequest validates a saml message using saml-schema-protocol-2_0.xsd, saml-schema-assertion-2_0.xsd, xenc-schema.xsd, xmldsig-core-schema.xsd,NaturalPersonShema.xsd

**Comment by lekarlr** [comment]
Thank you.

**Comment by lekarlr** [comment]
Hello, can you explain how to change <ds:SignatureMethod Algorithm and <ds:DigestMethod Algorithm in metadata ?

**Comment by AndreasHohnholt** [comment]
Hi, at the moment the only way to change the algorithm is to fork this projekt and to rewrite the EidasSigner.java
